[package]
name = "swdb"
version = "0.1.0"
authors = ["liubin <liubin01@zhihu.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.2"
crc32fast = "1.2"